# Generated by Django 4.2.11 on 2026-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_management', '0005_detection_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/annotated/'),
        ),
        migrations.AddField(
            model_name='detection',
            name='is_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='server_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
