# Generated by Django 4.2.11 on 2026-07-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_management', '0005_detection_history'),
        ('client', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_notifications', to='camera_management.camera')),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_notifications', to='camera_management.detection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
