# Generated by Django 5.2.16 on 2026-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0008_seed_existing_ttn_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Can see and manage every project, not just assigned ones.'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_supervisors', to='supervisor.project'),
        ),
    ]
