# Generated by Django 5.2.16 on 2026-08-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientauthtoken'),
        ('supervisor', '0010_grandfather_existing_supervisors_as_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
