name: SSH Debug

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Write key
        run: |
          printf '%s' "${{ secrets.SERVER_SSH_KEY }}" > key
          chmod 600 key
          
      - name: Test native SSH
        run: |
          ssh -vvv \
          -o StrictHostKeyChecking=no \
          -i key \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "whoami"
