name: SSH Debug

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check key fingerprint
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/key
          chmod 600 /tmp/key
          ssh-keygen -lf /tmp/key
            - name: Write key
              run: |
                echo "${{ secrets.SERVER_SSH_KEY }}" > key
                chmod 600 key
            
      - name: Test native SSH
        run: |
          ssh -vvv \
          -o StrictHostKeyChecking=no \
          -i key \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "whoami"
